(define (newton f f′ x0 ε)
  (define x 
    (- x0 (/ (f x0) (f′ x0))))
  (if (not (< (abs (- x x0)) ε))
      (newton f f′ x ε)
      x))
(define phi (/ (+ 1 (sqrt 5)) 2))
(define (golden f x0 x1 ε)
  (define x01 (- x1 (/ (- x1 x0) phi)))
  (define x11 (+ x0 (/ (- x1 x0) phi)))
  (define x (/ (+ x0 x1) 2))
  (if (>= (f x01) (f x11))
      (if (> (abs (- x1 x01)) ε)
          (golden f x01 x1 ε)
          x)
      (if (> (abs (- x11 x0)) ε)
          (golden f x0 x11 ε)
          x)))
          
