use lab10;
go

/* SET TRANSACTION ISOLATION LEVEL READ UNCOMMITTED;
BEGIN TRANSACTION;

SELECT * FROM CardBalance;
SELECT * FROM sys.dm_tran_locks;

COMMIT TRANSACTION;
go */



/* SET TRANSACTION ISOLATION LEVEL READ COMMITTED;
BEGIN TRANSACTION;

SELECT * FROM CardBalance;

WAITFOR DELAY '00:00:05';

SELECT * FROM CardBalance;
SELECT * FROM sys.dm_tran_locks;

COMMIT TRANSACTION;
go */



/* SET TRANSACTION ISOLATION LEVEL REPEATABLE READ
BEGIN TRANSACTION;

SELECT * FROM CardBalance  

WAITFOR DELAY '00:00:10'  

SELECT * FROM CardBalance
--SELECT * FROM sys.dm_tran_locks;

COMMIT TRANSACTION;
go */

/* SET TRANSACTION ISOLATION LEVEL SERIALIZABLE
BEGIN TRANSACTION;

SELECT * FROM CardBalance  

WAITFOR DELAY '00:00:05'  

SELECT * FROM CardBalance
--SELECT * FROM sys.dm_tran_locks;

COMMIT TRANSACTION;
go */